spring:
  application:
    name: short-link

  datasource:
    url: jdbc:mysql://localhost:3306/shortlink?allowPublicKeyRetrieval=true
    username: shortlink
    password: ${MYSQL_PASSWORD}

    hikari:
      # 核心：在连接池初始化每一个连接时，都执行这句 SQL
      # 这样池子里的所有连接，锁等待超时时间都被强制设为 5 秒
      # 理由：@Scheduled默认线程池 size = 1，定时任务串行一次卡 50 秒会堵住后面所有定时任务；
      #     清理跑凌晨2点低峰、几乎没有并发写，5秒足够。
      connection-init-sql: "SET SESSION innodb_lock_wait_timeout = 5"

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0
      connect-timeout: 3000ms
      timeout: 3000ms

  config:
    import: optional:file:./.env[.properties]

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

app:
  short-domain: http://s.xx.com/

short-link:
  batch-size: 500      # 每批删除数量
  max-round: 20        # 最大循环次数
  clean-cron: 0 0 2 * * ?
