spring:
  application:
    name: short-link

  datasource:
    url: jdbc:mysql://localhost:3306/shortlink?allowPublicKeyRetrieval=true
    username: shortlink
    password: ${MYSQL_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0
      connect-timeout: 3000ms
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
